Importing important libraries

In [ ]:
pip install opencv-python numpy scikit-learn scikit-image

In [ ]:
import os
import cv2
import numpy as np
import pickle
from sklearn.cluster import KMeans
from skimage.color import rgb2lab

Mounting the g drive

In [ ]:
# prompt: mount the drive

from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Import all the images

In [ ]:
# prompt: Import all the images stored in 5 folders (v1,v2,v3...v5) in path /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24 and store it

import os
import cv2
import numpy as np

# Define the base path
base_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24'

# Initialize an empty list to store the images
images = []
a=0

# Loop through the folders v1 to v5
for i in range(1, 6):
  folder_path = os.path.join(base_path, f'v{i}')
  # Check if the folder exists
  if os.path.exists(folder_path):
    # Loop through all files in the folder
    for filename in os.listdir(folder_path):
      if filename.endswith(('.jpg', '.jpeg', '.png')):  # Add other image extensions if needed
          img_path = os.path.join(folder_path, filename)
          # Load the image using OpenCV
          img = cv2.imread(img_path)
          if img is not None:  # Check if the image was loaded successfully
              images.append(img)
              a=a+1
              print("image done : ",a)
          else:
              print(f"Error loading image: {img_path}")
  else:
      print(f"Folder not found: {folder_path}")


# Now 'images' list contains all the loaded images
# You can perform further operations on the 'images' list.

# Example: Print the number of loaded images
print(f"Total number of images loaded: {len(images)}")

# Example: Display the first image
# if images:
#     cv2_imshow(images[0]) # Assuming cv2_imshow is defined in your environment


image done :  1
image done :  2
image done :  3
image done :  4
image done :  5
image done :  6
image done :  7
image done :  8
image done :  9
image done :  10
image done :  11
image done :  12
image done :  13
image done :  14
image done :  15
image done :  16
image done :  17
image done :  18
image done :  19
image done :  20
image done :  21
image done :  22
image done :  23
image done :  24
image done :  25
image done :  26
image done :  27
image done :  28
image done :  29
image done :  30
image done :  31
image done :  32
image done :  33
image done :  34
image done :  35
image done :  36
image done :  37
image done :  38
image done :  39
image done :  40
image done :  41
image done :  42
image done :  43
image done :  44
image done :  45
image done :  46
image done :  47
image done :  48
image done :  49
image done :  50
image done :  51
image done :  52
image done :  53
image done :  54
image done :  55
image done :  56
image done :  57
image done :  58
image done :  59
image 

In [ ]:
#Total no of images
len(images)

348

In [ ]:
# prompt: store images in pickle

import pickle

# Assuming 'images' list is already populated as in the previous code

# Specify the file path for saving the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/image_data.pickle'

# Save the 'images' list to a pickle file
try:
    with open(pickle_file_path, 'wb') as f:
        pickle.dump(images, f)
    print(f"Images successfully saved to {pickle_file_path}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


Images successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/image_data.pickle


In [ ]:
# prompt: import that pickle file

import pickle

# Specify the file path of the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/image_data.pickle'

try:
    # Open the pickle file in read binary mode
    with open(pickle_file_path, 'rb') as file:
        # Load the data from the pickle file
        loaded_images = pickle.load(file)

    # Now 'loaded_images' contains the data loaded from the pickle file
    print(f"Successfully loaded {len(loaded_images)} images from the pickle file.")

    # You can now work with the 'loaded_images' variable
    # Example: Print the shape of the first image
    # if loaded_images:
      #print(f"Shape of the first image: {loaded_images[0].shape}")
except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")


Successfully loaded 348 images from the pickle file.


**Performming K Means Clustering**

In [ ]:
train_images=loaded_images

In [ ]:
clustered_img = []
cluster_dict = {}

In [ ]:
for j in range(0,348):
  print("Image "+str(j)+" Started")
  k_mean_test_img=train_images[j]
  # Convert the image to the Lab color space
  lab_image = rgb2lab(k_mean_test_img)
  # Reshape the image into a 2D array
  X = lab_image.reshape((lab_image.shape[0] * lab_image.shape[1], 3))

  # Perform K-means clustering with 10 clusters
  kmeans = KMeans(n_clusters=10)
  kmeans.fit(X)

  # Get the cluster labels for each pixel
  labels = kmeans.labels_

  # Reshape the labels into a 2D array
  labels_2d = labels.reshape((lab_image.shape[0], lab_image.shape[1]))

  # Create a new image with the same dimensions as the original image
  new_image = np.zeros_like(k_mean_test_img)

  # Assign a different color to each cluster
  for i in range(10):
    new_image[labels_2d == i] = [255, 0, 0] if i == 0 else [0, 255, 0] if i == 1 else [0, 0, 255] if i == 2 else [255, 255, 0] if i == 3 else [0, 255, 255] if i == 4 else [255, 0, 255] if i == 5 else [128, 0, 0] if i == 6 else [0, 128, 0] if i == 7 else [0, 0, 128] if i == 8 else [128, 128, 0] if i == 9 else [0, 128, 128]
  # Find the area of each cluster
  areas = []
  for i in range(10):
    area = np.count_nonzero(labels_2d == i)
    areas.append(area)
  # Find the average RGB value for each cluster
  cluster_avg_rgb = []
  for i in range(10):
    cluster_pixels = k_mean_test_img[labels_2d == i]
    avg_r = np.mean(cluster_pixels[:, 0])
    avg_g = np.mean(cluster_pixels[:, 1])
    avg_b = np.mean(cluster_pixels[:, 2])
    cluster_avg_rgb.append([avg_r, avg_g, avg_b])
  # Create a new image with the same dimensions as the original image
  segmented_image = np.zeros_like(k_mean_test_img)

  # Assign each pixel of respective clusters with AVG RGB value of each cluster
  for i in range(10):
    segmented_image[labels_2d == i] = cluster_avg_rgb[i]
  clustered_img.append(segmented_image)
  cluster_dict_len=len(cluster_dict)
  for i in range(10):
    cluster_dict[i+cluster_dict_len] = {
      "avg_rgb": cluster_avg_rgb[i],
      "area": areas[i]
    }
  print("Image "+str(j)+" Ended")


Image 0 Started
Image 0 Ended
Image 1 Started
Image 1 Ended
Image 2 Started
Image 2 Ended
Image 3 Started
Image 3 Ended
Image 4 Started
Image 4 Ended
Image 5 Started
Image 5 Ended
Image 6 Started
Image 6 Ended
Image 7 Started
Image 7 Ended
Image 8 Started
Image 8 Ended
Image 9 Started
Image 9 Ended
Image 10 Started
Image 10 Ended
Image 11 Started
Image 11 Ended
Image 12 Started
Image 12 Ended
Image 13 Started
Image 13 Ended
Image 14 Started
Image 14 Ended
Image 15 Started
Image 15 Ended
Image 16 Started
Image 16 Ended
Image 17 Started
Image 17 Ended
Image 18 Started
Image 18 Ended
Image 19 Started
Image 19 Ended
Image 20 Started
Image 20 Ended
Image 21 Started
Image 21 Ended
Image 22 Started
Image 22 Ended
Image 23 Started
Image 23 Ended
Image 24 Started
Image 24 Ended
Image 25 Started
Image 25 Ended
Image 26 Started
Image 26 Ended
Image 27 Started
Image 27 Ended
Image 28 Started
Image 28 Ended
Image 29 Started
Image 29 Ended
Image 30 Started
Image 30 Ended
Image 31 Started
Image 31 En

In [ ]:
# prompt: store it in pickle

import pickle

# Specify the file path for saving the pickle file
pickle_file_path_clustered_img = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_img_data.pickle'

# Save the 'clustered_img' list to a pickle file
try:
    with open(pickle_file_path_clustered_img, 'wb') as f:
        pickle.dump(clustered_img, f)
    print(f"clustered_img successfully saved to {pickle_file_path_clustered_img}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


# Specify the file path for saving the pickle file
pickle_file_path_cluster_dict = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/cluster_dict_data.pickle'

# Save the 'cluster_dict' dictionary to a pickle file
try:
    with open(pickle_file_path_cluster_dict, 'wb') as f:
        pickle.dump(cluster_dict, f)
    print(f"cluster_dict successfully saved to {pickle_file_path_cluster_dict}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


clustered_img successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_img_data.pickle
cluster_dict successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/cluster_dict_data.pickle


In [ ]:
clustered_img

[array([[[230, 231, 232],
         [230, 231, 232],
         [230, 231, 232],
         ...,
         [230, 231, 232],
         [230, 231, 232],
         [230, 231, 232]],
 
        [[230, 231, 232],
         [230, 231, 232],
         [230, 231, 232],
         ...,
         [230, 231, 232],
         [230, 231, 232],
         [230, 231, 232]],
 
        [[230, 231, 232],
         [230, 231, 232],
         [230, 231, 232],
         ...,
         [230, 231, 232],
         [230, 231, 232],
         [230, 231, 232]],
 
        ...,
 
        [[ 20,  65,  44],
         [ 20,  65,  44],
         [ 20,  65,  44],
         ...,
         [ 42, 100,  83],
         [ 42, 100,  83],
         [ 42, 100,  83]],
 
        [[ 20,  65,  44],
         [ 20,  65,  44],
         [ 20,  65,  44],
         ...,
         [ 42, 100,  83],
         [ 42, 100,  83],
         [ 42, 100,  83]],
 
        [[ 20,  65,  44],
         [ 20,  65,  44],
         [ 20,  65,  44],
         ...,
         [ 42, 100,  83],
  

In [ ]:
cluster_dict

{0: {'avg_rgb': [42.49391225622191, 100.40356911187541, 83.81929037767812],
  'area': 214283},
 1: {'avg_rgb': [230.0915973159028, 231.48143875952826, 232.72329642591035],
  'area': 460341},
 2: {'avg_rgb': [19.993003074624294, 35.99739950001437, 28.275559610356023],
  'area': 139204},
 3: {'avg_rgb': [83.63456203552478, 99.96885134448725, 90.35069978978956],
  'area': 127967},
 4: {'avg_rgb': [26.205008131517985, 93.91795312159174, 65.08909603474602],
  'area': 362171},
 5: {'avg_rgb': [69.07160623118209, 54.891870663699436, 114.45673517476109],
  'area': 7639},
 6: {'avg_rgb': [40.978249169957856, 118.34771797058491, 89.04108398122159],
  'area': 362331},
 7: {'avg_rgb': [58.85543422478189, 73.50327878200376, 67.77652249529567],
  'area': 140296},
 8: {'avg_rgb': [122.34835580992855, 139.63738711722672, 130.94639888959335],
  'area': 58357},
 9: {'avg_rgb': [20.98698993857772, 65.87570885192562, 44.06680654986112],
  'area': 216371},
 10: {'avg_rgb': [19.876237623762375, 34.771057233

In [ ]:
# prompt: import both pickle files

import pickle

# Specify the file paths of the pickle files
pickle_file_path_clustered_img = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_img_data.pickle'
pickle_file_path_cluster_dict = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/cluster_dict_data.pickle'


try:
    # Open the first pickle file in read binary mode
    with open(pickle_file_path_clustered_img, 'rb') as file:
        # Load the data from the pickle file
        loaded_clustered_img = pickle.load(file)

    print(f"Successfully loaded clustered images from {pickle_file_path_clustered_img}")

except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path_clustered_img}")
except Exception as e:
    print(f"An error occurred while loading the first pickle file: {e}")


try:
    # Open the second pickle file in read binary mode
    with open(pickle_file_path_cluster_dict, 'rb') as file:
        # Load the data from the pickle file
        loaded_cluster_dict = pickle.load(file)

    print(f"Successfully loaded cluster dictionary from {pickle_file_path_cluster_dict}")

except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path_cluster_dict}")
except Exception as e:
    print(f"An error occurred while loading the second pickle file: {e}")


Successfully loaded clustered images from /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_img_data.pickle
Successfully loaded cluster dictionary from /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/cluster_dict_data.pickle


In [ ]:
len(loaded_cluster_dict)

3480

In [ ]:
segment1_list = []
for i in range(len(loaded_cluster_dict)):
  segment1_list.append(loaded_cluster_dict[i]["avg_rgb"])


In [ ]:
segment1_list_copy=segment1_list

In [ ]:
segment1_list_copy

[[42.49391225622191, 100.40356911187541, 83.81929037767812],
 [230.0915973159028, 231.48143875952826, 232.72329642591035],
 [19.993003074624294, 35.99739950001437, 28.275559610356023],
 [83.63456203552478, 99.96885134448725, 90.35069978978956],
 [26.205008131517985, 93.91795312159174, 65.08909603474602],
 [69.07160623118209, 54.891870663699436, 114.45673517476109],
 [40.978249169957856, 118.34771797058491, 89.04108398122159],
 [58.85543422478189, 73.50327878200376, 67.77652249529567],
 [122.34835580992855, 139.63738711722672, 130.94639888959335],
 [20.98698993857772, 65.87570885192562, 44.06680654986112],
 [19.876237623762375, 34.77105723392852, 27.44687032805845],
 [230.12533746712418, 231.34733640464702, 232.68398272168324],
 [41.65574390071922, 117.9364461994077, 89.26048230150896],
 [83.1044120016264, 99.27885906297709, 90.01123138650853],
 [22.17430163401914, 65.60414583656053, 45.194185877305394],
 [42.9437993089814, 100.56067660698778, 84.67700885021155],
 [122.00010216765712, 1

In [ ]:
len(segment1_list_copy)

3480

In [ ]:

X = np.array(segment1_list_copy)
kmeans = KMeans(n_clusters=20)
kmeans.fit(X)
labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_
print(labels)
print(cluster_centers)

[12  2 15 ... 16 16 12]
[[ 34.7169874   61.64706582  50.65829416]
 [ 88.57490826 149.21536068 166.51124805]
 [241.21088636 241.68483731 236.27506498]
 [ 43.07250985  97.04345212 180.42242735]
 [ 46.72335068 144.27341694  64.7619152 ]
 [203.06809348 194.48757652  78.50513481]
 [ 44.22176289 130.7327503  135.96763327]
 [ 68.59164876 191.76500197 208.26289413]
 [ 97.02851686 213.72104448  59.34492911]
 [ 56.02989217 187.30973304 130.27723343]
 [ 46.70796321  45.20144112 120.52433813]
 [ 94.73911845 109.54846635 110.45661782]
 [ 45.15236943  95.79363129  83.35919177]
 [221.11648122 176.71550174 164.79536142]
 [146.32877574 187.95401382 197.52983926]
 [  8.90224029  12.956035    12.08323205]
 [153.02882783 155.87770335 135.21647323]
 [214.78102258 218.14598813 170.5294543 ]
 [ 26.3956423  150.8765602  217.19811981]
 [132.00683975 134.36782017  49.50610615]]


In [ ]:
len(labels)

3480

In [ ]:
clustered_dict_segmentation2={}
for i in range(len(cluster_centers)):
  clustered_dict_segmentation2[i]={
      "rgb value":cluster_centers[i],
      # "size": cluster_sizes[i]
  }

In [ ]:
clustered_dict_segmentation2

{0: {'rgb value': array([34.7169874 , 61.64706582, 50.65829416])},
 1: {'rgb value': array([ 88.57490826, 149.21536068, 166.51124805])},
 2: {'rgb value': array([241.21088636, 241.68483731, 236.27506498])},
 3: {'rgb value': array([ 43.07250985,  97.04345212, 180.42242735])},
 4: {'rgb value': array([ 46.72335068, 144.27341694,  64.7619152 ])},
 5: {'rgb value': array([203.06809348, 194.48757652,  78.50513481])},
 6: {'rgb value': array([ 44.22176289, 130.7327503 , 135.96763327])},
 7: {'rgb value': array([ 68.59164876, 191.76500197, 208.26289413])},
 8: {'rgb value': array([ 97.02851686, 213.72104448,  59.34492911])},
 9: {'rgb value': array([ 56.02989217, 187.30973304, 130.27723343])},
 10: {'rgb value': array([ 46.70796321,  45.20144112, 120.52433813])},
 11: {'rgb value': array([ 94.73911845, 109.54846635, 110.45661782])},
 12: {'rgb value': array([45.15236943, 95.79363129, 83.35919177])},
 13: {'rgb value': array([221.11648122, 176.71550174, 164.79536142])},
 14: {'rgb value': arr

In [ ]:


# Specify the file path for saving the pickle file
pickle_file_path_clustered_dict_segmentation2 = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_dict_segmentation2.pickle'

# Save the 'clustered_dict_segmentation2' dictionary to a pickle file
try:
    with open(pickle_file_path_clustered_dict_segmentation2, 'wb') as f:
        pickle.dump(clustered_dict_segmentation2, f)
    print(f"clustered_dict_segmentation2 successfully saved to {pickle_file_path_clustered_dict_segmentation2}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


clustered_dict_segmentation2 successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_dict_segmentation2.pickle


In [ ]:
#Store Labels

# Assuming 'labels' is the variable containing your labels
# Example: labels = [1, 0, 1, 1, 0, ...]


# Specify the file path for saving the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/labels.pickle'

# Save the 'labels' list to a pickle file
try:
    with open(pickle_file_path, 'wb') as f:
        pickle.dump(labels, f)
    print(f"Labels successfully saved to {pickle_file_path}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


Labels successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/labels.pickle


# **Code For Neural Network Trainning**

Read clustered_dict_segmentation2 from pickle

In [ ]:
# prompt: Read clustered_dict_segmentation2 from pickle

import pickle

# Specify the file path of the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/clustered_dict_segmentation2.pickle'

try:
    # Open the pickle file in read binary mode
    with open(pickle_file_path, 'rb') as file:
        # Load the data from the pickle file
        clustered_dict_segmentation2 = pickle.load(file)

    # Now 'clustered_dict_segmentation2' contains the data loaded from the pickle file
    print(f"Successfully loaded clustered_dict_segmentation2 from the pickle file.")

    # You can now work with the 'clustered_dict_segmentation2' variable
    # Example: Print the contents of the dictionary
    # print(clustered_dict_segmentation2)
except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")


Successfully loaded clustered_dict_segmentation2 from the pickle file.


In [ ]:
# prompt: read labels from pickle

import pickle

# Specify the file path of the pickle file containing the labels
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/labels.pickle'

try:
    # Open the pickle file in read binary mode
    with open(pickle_file_path, 'rb') as file:
        # Load the data from the pickle file
        labels = pickle.load(file)

    # Now 'labels' contains the labels loaded from the pickle file
    print(f"Successfully loaded labels from the pickle file.")

    # You can now work with the 'labels' variable
    # Example: Print the loaded labels
    print(labels)

except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")


Successfully loaded labels from the pickle file.
[12  2 15 ... 16 16 12]


Create New List To Store Expected Output

In [ ]:
expected_output_list=[]

In [ ]:
for i in range(len(labels)):
  expected_output_list.append(labels[i])

Store expected output list in pickle

In [ ]:
# prompt: Store expected output list in pickle


# Assuming 'expected_output_list' is already defined

# Specify the file path for saving the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/expected_output_list.pickle'

# Save the 'expected_output_list' list to a pickle file
try:
    with open(pickle_file_path, 'wb') as f:
        pickle.dump(expected_output_list, f)
    print(f"expected_output_list successfully saved to {pickle_file_path}")
except Exception as e:
    print(f"An error occurred while saving the pickle file: {e}")


expected_output_list successfully saved to /content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/expected_output_list.pickle


Read expected_output_list from pickle

In [ ]:
# prompt: Read expected_output_list from pickle


# Specify the file path of the pickle file
pickle_file_path = '/content/drive/MyDrive/Capstone/DATA_SET/TEMP_IMG_COL/FINAL/2023-24/expected_output_list.pickle'

try:
    # Open the pickle file in read binary mode
    with open(pickle_file_path, 'rb') as file:
        # Load the data from the pickle file
        expected_output_list = pickle.load(file)

    # Now 'expected_output_list' contains the data loaded from the pickle file
    print(f"Successfully loaded expected_output_list from the pickle file.")

    # You can now work with the 'expected_output_list' variable
    # Example: Print the first 10 elements of the list
    print(expected_output_list[:10])
except FileNotFoundError:
    print(f"Error: Pickle file not found at {pickle_file_path}")
except Exception as e:
    print(f"An error occurred: {e}")


Successfully loaded expected_output_list from the pickle file.
[12, 2, 15, 11, 12, 10, 12, 12, 16, 0]


In [ ]:
len (segment1_list_copy)


3480

In [ ]:
len(labels)

3480

In [ ]:
split_index=len(expected_output_list)//2
split_index

1740

**Input in : segment1_list_copy**

**Output is : expected_output_list**

In [ ]:
import numpy as np
import tensorflow as tf

#Define Model
model=tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(3,)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(20,activation='softmax')
])

#Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

#Define Trainning Data
X_train= np.array(segment1_list_copy[:split_index])
y_train= np.array(expected_output_list[:split_index])

#Define Testing Data
X_test= np.array(segment1_list_copy[split_index:])
y_test= np.array(expected_output_list[split_index:])

#Train the model
model.fit(
    X_train,
    y_train,
    epochs=100
)

#Evaluate the model
model.evaluate(X_test,y_test)

Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


55/55 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.1356 - loss: 15.9300
Epoch 2/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4800 - loss: 1.6569
Epoch 3/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4679 - loss: 1.3703
Epoch 4/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4948 - loss: 1.3613
Epoch 5/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4503 - loss: 1.5042
Epoch 6/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5121 - loss: 1.2885
Epoch 7/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5731 - loss: 1.1044
Epoch 8/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5254 - loss: 1.2182
Epoch 9/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5314 - loss: 1.1989
Epoch 10/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5599 - loss: 1.1068
Epoch 11/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5733 - loss: 1.1025
Epoch 12/100
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6012 - l

[0.868661105632782, 0.7137930989265442]

# Crop Percentage Prediction In An Image

Defining Crop names

In [ ]:
crop_name= [
    "green field 1",
    "street",
    "red merigold",
    "red merigold",
    "green plants (early stage 1)",
    "green plants (early stage 2)",
    "outside area",
    "red merigold (not fully grown)",
    "outside area",
    "sky or water",
    "outside area",
    "Rajgira (Chrysanthemum)",
    "green plants (early stage 2)",
    "sky or water",
    "green plants (early stage 2)",
    "yellow merigold",
    "yellow merigold",
    "deep green plants (early stage 1)",
    "deep green plants (early stage 2)",
    "Rajgira (Chrysanthemum)"
]

PYTHONCODE FOR CALCULATING FLOWER VARIETY AREA PERCENTAGE IN AN INPUT IMAGE


In [ ]:
from google.colab import drive
drive._mount('/content/drive')


ValueError: mount failed

In [ ]:
# prompt: import a image from drive and store in prediction_input_image


import cv2
import numpy as np

# Specify the path to your image file in Google Drive
image_path = '/content/drive/MyDrive/your_image.jpg'  # Replace with the actual path

# Load the image using OpenCV
prediction_input_image = cv2.imread(image_path)

# Check if the image was loaded successfully
if prediction_input_image is not None:
    print("Image loaded successfully!")
    # Now you can use prediction_input_image for your prediction task
else:
    print(f"Error loading image: {image_path}")


In [ ]:
prediction_input_image_copy=prediction_input_image

In [ ]:
# Reshape input_image_copy to a 2D array
prediction_input_image_copy_flattened = prediction_input_image_copy.reshape(-1, 3)

# Predict clusters for all pixels at once
prediction_predicted_clusters = model.predict(prediction_input_image_copy_flattened)

# Find the index of the maximum value for each prediction
prediction_index_of_max_value = np.argmax(prediction_predicted_clusters, axis=1)

# Create a lookup table for RGB values
prediction_rgb_lookup_table = np.array([cluster_dict_segmentation2[i]['rgb value'] for i in range(len(cluster_dict_segmentation2))])

# Assign the corresponding RGB values to each pixel
prediction_input_image_copy_flattened[:] = prediction_rgb_lookup_table[prediction_index_of_max_value]

# Reshape back to the original dimensions
prediction_input_image_copy = prediction_input_image_copy_flattened.reshape(prediction_input_image_copy.shape)


In [ ]:
import numpy as np

# Initialize cluster counts dictionary
cluster_counts = {}
for i in range(len(cluster_dict_segmentation2)):
    cluster_counts[i] = np.count_nonzero(prediction_index_of_max_value == i)

# Print cluster counts
print(cluster_counts)

In [ ]:
cluster_names = set(crop_name[i] for i in range(len(crop_name)))
cluster_pixel_counts = {}
for name in cluster_names:

    cluster_index = crop_name.index(name)
    cluster_pixel_counts[name] = cluster_counts[cluster_index]

# Print cluster pixel counts
print(cluster_pixel_counts)

In [ ]:
len(cluster_pixel_counts)

**PYTHON CODE FOR HED EDGE DETECTION**

Image cropping function definition


In [ ]:
class CropLayer(object):
    def __init__(self, params, blobs):
        # initialize our starting and ending (x, y)-coordinates of the crop
        self.startX = 0
        self.startY = 0
        self.endX = 0
        self.endY = 0

    def getMemoryShapes(self, inputs):
        # the crop layer will receive two inputs — we need to crop
        # the first input blob to match the shape of the second one,
        # keeping the batch size and number of channels
        (inputShape, targetShape) = (inputs[0], inputs[1])
        (batchSize, numChannels) = (inputShape[0], inputShape[1])
        (H, W) = (targetShape[2], targetShape[3])

        # compute the starting and ending crop coordinates
        self.startX = int((inputShape[3] - targetShape[3]) / 2)
        self.startY = int((inputShape[2] - targetShape[2]) / 2)
        self.endX = self.startX + W
        self.endY = self.startY + H

        # return the shape of the volume (we'll perform the actual crop during the forward pass)
        return [[batchSize, numChannels, H, W]]

    def forward(self, inputs):
        # use the derived (x, y)-coordinates to perform the crop
        return [inputs[0][:, :, self.startY:self.endY, self.startX:self.endX]]


In [ ]:
protoPath = "/content/drive/MyDrive/HED/deploy.prototxt"
modelPath = "/content/drive/MyDrive/HED/hed_pretrained_bsds.caffemodel"


In [ ]:
# Load the Caffe model
net = cv2.dnn.readNetFromCaffe(protoPath, modelPath)

In [ ]:
# register our crop layer with the model
cv2.dnn_registerLayer("Crop", CropLayer)


Break the images into different components.
Raw same image is stored as img

In [ ]:
# Load the input image and grab its dimensions, for future use while defining the blob
img = cv2.imread("/content/drive/MyDrive/IMG_DATASET/2023-24/V5/scene16451.png")
plt.imshow(img)
(H,W)=img.shape[:2]
mean_pixel_values = np.average(img, axis=(0,1))
blob = cv2.dnn.blobFromImage(img, scalefactor=0.7, size=(W, H),
                             mean=(mean_pixel_values[0], mean_pixel_values[1], mean_pixel_values[2]),
                             swapRB=False, crop=False)
blob_for_plot=np.moveaxis(blob[0,:,:,:],0,2)


In [ ]:
#set the blob as the input to the network and perform a forward pass to compute the edges
net.setInput(blob)
hed = net.forward()
hed = hed[0,0,:,:]  # Drop the other axes
hed = (255 * hed).astype("uint8")  # rescale to 0-255

**PYTHON CODE FOR CCL**

In [ ]:
# Apply Gaussian blur, grayscale conversion, and Otsu's thresholding
blur = cv2.GaussianBlur(hed, (3,3), 0)
thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

# Perform connected component labelling
n_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(thresh, connectivity=4)
colors = np.random.randint(0, 255, size=(n_labels, 3), dtype=np.uint8)
colors[0] = [0, 0, 0]  # black background

# Visualize the components with colored labels
false_colors = colors[labels]


# Obtain centroids
false_colors_centroid = false_colors.copy()
for centroid in centroids:
    cv2.drawMarker(false_colors_centroid, (int(centroid[0]), int(centroid[1])),
                   color=(255, 255, 255), markerType=cv2.MARKER_CROSS)

# Remove small objects
MIN_AREA = 50
false_colors_area_filtered = false_colors.copy()
for i, centroid in enumerate(centroids[1:], start=1):  # Start from 1 to skip the background
    area = stats[i, 4]
    if area > MIN_AREA:
        cv2.drawMarker(false_colors_area_filtered, (int(centroid[0]), int(centroid[1])),
                       color=(255, 255, 255), markerType=cv2.MARKER_CROSS)



**Python code for drawing rectangle to the area which is underdeveloped or outside area**

In [ ]:
for component_label in all_components:
    print(f"Component no: {component_label}")
    area = stats[component_label, cv2.CC_STAT_AREA]
    if area <= 0.01*total_area:
      continue

    # Find pixels belonging to the current component
    component_pixels = np.argwhere(labels == component_label)

    # Extract RGB values for the component pixels
    component_rgb_values = crop_type_prediction_img[component_pixels[:, 0], component_pixels[:, 1]]

    # Predict clusters for all RGB values in the component
    predicted_clusters = model.predict(component_rgb_values)

    # Determine the most likely crop for each pixel
    predicted_crop_indices = np.argmax(predicted_clusters, axis=1)
    predicted_crops = np.take(crop_name, predicted_crop_indices)

    # Count defected pixels
    defected_pixels = np.isin(predicted_crops, ["green plants (early stage 1)", "red merigold (not fully grown)",
                                                "green plants (early stage 2)", "outside area", "sky or water",
                                                "deep green plants (early stage 1)"])
    defected_count = np.sum(defected_pixels)



In [ ]:
 # Check if defected count is within bounds
lower_bound = 0.4 * len(component_pixels)
upper_bound = 1.0 * len(component_pixels)
if lower_bound <= defected_count <= upper_bound:
    print("Area Detected")
        # Get bounding box coordinates for the component
        #x, y, w, h = cv2.boundingRect(component_pixels)
        # Draw bounding box on the image
        #cv2.rectangle(crop_type_prediction_img, (x, y), (x + w, y + h), (0, 255, 0), 5)
    x=np.min(component_pixels[:,0])
    y=np.min(component_pixels[:,1])
    w=np.max(component_pixels[:,0])
    h=np.max(component_pixels[:,1])
# Draw bounding box on the image
    cv2.rectangle(crop_type_prediction_img, (y, x), (h, w), (255, 0, 0), 5)

In [ ]:
print("hello")

hello
